src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'integer')]
    private $status;

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'parent_id')]
    private $parent;

    #[ORM\OneToMany(mappedBy: 'parent', targetEntity: self::class)]
    private $parent_id;

    #[ORM\OneToMany(mappedBy: 'category', targetEntity: Product::class)]
    private $products;

    public function __construct()
    {
        $this->parent_id = new ArrayCollection();
        $this->products = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStatus(): ?string
    {
        if ($this->status)
            return 'Active';

        return 'Draft';
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getParentId(): Collection
    {
        return $this->parent_id;
    }

    public function addParentId(self $parentId): self
    {
        if (!$this->parent_id->contains($parentId)) {
            $this->parent_id[] = $parentId;
            $parentId->setParent($this);
        }

        return $this;
    }

    public function removeParentId(self $parentId): self
    {
        if ($this->parent_id->removeElement($parentId)) {
            // set the owning side to null (unless already changed)
            if ($parentId->getParent() === $this) {
                $parentId->setParent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setCategory($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getCategory() === $this) {
                $product->setCategory(null);
            }
        }

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $unique_code;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'integer')]
    private $price;

    #[ORM\Column(type: 'integer')]
    private $status;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private $category;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: ProductToOrder::class)]
    private $productToOrders;

    public function __construct()
    {
        $this->productToOrders = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUniqueCode(): ?string
    {
        return $this->unique_code;
    }

    public function setUniqueCode(string $unique_code): self
    {
        $this->unique_code = $unique_code;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getStatus(): ?string
    {
        if ($this->status)
            return 'Active';

        return 'Draft';
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, ProductToOrder>
     */
    public function getProductToOrders(): Collection
    {
        return $this->productToOrders;
    }

    public function addProductToOrder(ProductToOrder $productToOrder): self
    {
        if (!$this->productToOrders->contains($productToOrder)) {
            $this->productToOrders[] = $productToOrder;
            $productToOrder->setProduct($this);
        }

        return $this;
    }

    public function removeProductToOrder(ProductToOrder $productToOrder): self
    {
        if ($this->productToOrders->removeElement($productToOrder)) {
            // set the owning side to null (unless already changed)
            if ($productToOrder->getProduct() === $this) {
                $productToOrder->setProduct(null);
            }
        }

        return $this;
    }
}

src/Form/CategoryType.php
<?php

namespace App\Form;

use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('status', ChoiceType::class, [
                'choices' => [
                    'Active' => 1,
                    'Draft' => 0,
                ]
            ])
            ->add('parent');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Category::class,
        ]);
    }
}

src/Controller/CategoryController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Form\CategoryType;
use App\Repository\CategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/category')]
class CategoryController extends AbstractController
{
    #[Route('/', name: 'app_category_index', methods: ['GET'])]
    public function index(CategoryRepository $categoryRepository): Response
    {
        return $this->render('category/index.html.twig', [
            'categories' => $categoryRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_category_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CategoryRepository $categoryRepository): Response
    {
        $category = new Category();
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $categoryRepository->add($category, true);

            return $this->redirectToRoute('app_category_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('category/new.html.twig', [
            'category' => $category,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_category_show', methods: ['GET'])]
    public function show(Category $category): Response
    {
        return $this->render('category/show.html.twig', [
            'category' => $category,
            'products' => $category->getProducts(),
        ]);
    }

    #[Route('/{id}/edit', name: 'app_category_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Category $category, CategoryRepository $categoryRepository): Response
    {
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $categoryRepository->add($category, true);

            return $this->redirectToRoute('app_category_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('category/edit.html.twig', [
            'category' => $category,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_category_delete', methods: ['POST'])]
    public function delete(Request $request, Category $category, CategoryRepository $categoryRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$category->getId(), $request->request->get('_token'))) {
            $categoryRepository->remove($category, true);
        }

        return $this->redirectToRoute('app_category_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/category/_delete_form.html.twig
<form method="post" action="{{ path('app_category_delete', {'id': category.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ category.id) }}">
    <button class="btn">Delete</button>
</form>

templates/category/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Category{% endblock %}

{% block body %}
    <h1>Edit Category</h1>

    {{ include('category/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_category_index') }}">back to list</a>

    {{ include('category/_delete_form.html.twig') }}
{% endblock %}

templates/category/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Category index{% endblock %}

{% block body %}
<!-- ...:::: Start Breadcrumb Section:::... -->
<div class="breadcrumb-section">
    <div class="breadcrumb-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-12 d-flex justify-content-between justify-content-md-between  align-items-center flex-md-row flex-column">
                    <h3 class="breadcrumb-title">Categories</h3>
                    <h4><a href="{{ path('app_category_new') }}">Create new</a></h4>
                </div>
            </div>
        </div>
    </div>
</div> <!-- ...:::: End Breadcrumb Section:::... -->
<div class="container">
    <div class="row ">
        <div class="col-12">
            <div class="blog-full-width-wrapper">
                <div class="row">
                    {% for category in categories %}
                    <div class="col-lg-4 col-md-6 col-12">
                        <!-- Start Blog Grid Single -->
                        <div class="blog-feed-single">
                            <a href="{{ path('app_category_show', {'id': category.id}) }}" class="blog-feed-img-link">
                                <img src="assets/images/blog_images/aments_blog_01.jpg" alt=""
                                     class="blog-feed-img">
                            </a>
                            <div class="blog-feed-content">
                                <div class="blog-feed-post-meta">
                                    <span>Category ID:</span>
                                    <a href="" class="blog-feed-post-meta-author">{{ category.id }}</a>
                                </div>
                                <div class="blog-feed-post-meta">
                                    <span>Status:</span>
                                    <a href="" class="blog-feed-post-meta-author">{{ category.status }}</a>
                                </div>
                                <h5 class="blog-feed-link"><a href="{{ path('app_category_show', {'id': category.id}) }}">{{ category.name }}</a></h5>
                                <a href="{{ path('app_category_edit', {'id': category.id}) }}">edit</a>
                            </div>
                        </div>
                        <!-- End Blog Grid Single -->
                    </div>
                    {% else %}
                        <tr>
                            <td colspan="4">no records found</td>
                        </tr>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/category/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Category{% endblock %}

{% block body %}
    <h1>Create new Category</h1>

    {{ include('category/_form.html.twig') }}

    <a href="{{ path('app_category_index') }}">back to list</a>
{% endblock %}

templates/category/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Category {{ category.name }}{% endblock %}

{% block body %}
    <h1>Category {{ category.name }}</h1>
    <div class="container">
        <div class="row ">
            <div class="col-12">
                <div class="blog-full-width-wrapper">
                    <div class="row">
                        {% for product in products %}
                            <div class="col-lg-4 col-md-6 col-12">
                                <!-- Start Blog Grid Single -->
                                <div class="blog-feed-single">
                                    <a href="{{ path('app_product_show', {'id': product.id}) }}"
                                       class="blog-feed-img-link">
                                        <img src="assets/images/blog_images/aments_blog_01.jpg" alt=""
                                             class="blog-feed-img">
                                    </a>
                                    <div class="blog-feed-content">
                                        <div class="blog-feed-post-meta">
                                            <span>Product ID:</span>
                                            <a href="{{ path('app_product_show', {'id': product.id}) }}" class="blog-feed-post-meta-author">{{ product.id }}</a>
                                        </div>
                                        <div class="blog-feed-post-meta">
                                            <span>Category:</span>
                                            <a href="{{ path('app_category_show', {'id': category.id}) }}" class="blog-feed-post-meta-author">{{ category.name }}</a>
                                        </div>
                                        <div class="blog-feed-post-meta">
                                            <span>Unique CODE:</span>
                                            <a href="" class="blog-feed-post-meta-author">{{ product.uniqueCode }}</a>
                                        </div>
                                        <div class="blog-feed-post-meta">
                                            <span>Status:</span>
                                            <a href="" class="blog-feed-post-meta-author">{{ product.status }}</a>
                                        </div>
                                        <h5 class="blog-feed-link"><a
                                                    href="{{ path('app_product_show', {'id': product.id}) }}">{{ product.name }}</a>
                                        </h5>
                                        <a href="{{ path('app_product_edit', {'id': product.id}) }}">edit</a>
                                    </div>
                                </div>
                                <!-- End Blog Grid Single -->
                            </div>
                        {% else %}
                            <tr>
                                <td colspan="4">no records found</td>
                            </tr>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/category/view.html.twig
{% extends 'base.html.twig' %}
  {% block body %}
      <!-- ...:::: Start Breadcrumb Section:::... -->
      <div class="breadcrumb-section">
          <div class="breadcrumb-wrapper">
              <div class="container">
                  <div class="row">
                      <div class="col-12 d-flex justify-content-between justify-content-md-between  align-items-center flex-md-row flex-column">
                          <h3 class="breadcrumb-title">Category </h3>
                      </div>
                  </div>
              </div>
          </div>
      </div> <!-- ...:::: End Breadcrumb Section:::... -->
      <div class="container">
          <div class="row ">
              <div class="col-12">

                  <div class="blog-full-width-wrapper">
                      <div class="row">

                          <div class="col-lg-4 col-md-6 col-12">
                              <!-- Start Blog Grid Single -->
                              <div class="blog-feed-single">
                                  <a href="blog-single-sidebar-left.html" class="blog-feed-img-link">
                                      <img src="assets/images/blog_images/aments_blog_01.jpg" alt=""
                                           class="blog-feed-img">
                                  </a>
                                  <div class="blog-feed-content">
                                      <div class="blog-feed-post-meta">
                                          <span>By:</span>
                                          <a href="" class="blog-feed-post-meta-author">Admin</a> -
                                          <a href="" class="blog-feed-post-meta-date">Sep 14, 2020</a>
                                      </div>
                                      <h5 class="blog-feed-link"><a href="blog-single-sidebar-left.html">Lorem ipsum
                                              dolor amet cons adipisicing elit</a></h5>
                                  </div>
                              </div>
                              <!-- End Blog Grid Single -->
                          </div>

                      </div>

                      <!-- Start Pagination -->
                      <div class="page-pagination text-center">
                          <ul>
                              <li><a href="#">Previous</a></li>
                              <li><a class="active" href="#">1</a></li>
                              <li><a href="#">2</a></li>
                              <li><a href="#">3</a></li>
                              <li><a href="#">Next</a></li>
                          </ul>
                      </div> <!-- End Pagination -->
                  </div>
              </div>
          </div>
  {% endblock %}